---

- name: download badblood from github
  win_shell: | 
    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
    $Url = 'https://github.com/davidprowe/BadBlood/archive/master.zip'
    $ZipFile = 'C:\badblood.zip'
    Invoke-WebRequest -Uri $Url -OutFile $ZipFile 

- name: unzip badblood
  win_unzip:
    src: 'C:\badblood.zip'
    dest: 'C:\badblood'
    creates: 'C:\badblood\Invoke-BadBlood.ps1'

- name: copy custom headless installer
  win_copy:
    force: yes
    src: 'invoke-badblood.ps1'
    dest: 'C:\badblood\Invoke-BadBlood.ps1'
