
- name: Create folder directory for macros configuration
  file:
    path: "{{ item }}"
    state: directory
    owner: splunk
    group: splunk
    recurse: yes
  with_items:
    - /opt/splunk/etc/apps/macros_app/local/

- name: Create metadata folder directory for macros app permissions to be set to GLOBAL
  file:
    path: "{{ item }}"
    state: directory
    owner: splunk
    group: splunk
    recurse: yes
  with_items:
    - /opt/splunk/etc/apps/macros_app/metadata/

- name: copy macros_metadata.conf to splunk server
  copy:
    src: macros_metadata.conf
    dest: /opt/splunk/etc/apps/macros_app/metadata/local.meta
    owner: splunk
    group: splunk

- name: copy macros.conf to splunk server
  copy:
    src: macros.conf
    dest: /opt/splunk/etc/apps/macros_app/local/macros.conf
    owner: splunk
    group: splunk
  notify: restart splunk
